In [39]:
import pandas as pd

In [40]:
import pandas as pd

df = pd.read_csv("../data/resumes/Resume.csv")

df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [41]:
df.columns

Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='object')

In [42]:
df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [43]:
print(df['Resume_str'][0])

         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate

HR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate     Designed and created marketing collateral for sales meetings, trade shows and company executives.  Managed the in-house advertising program consisting of print and media collateral pieces.  Assisted in the complete design and launch of the company's website in 2 months.  Created an official company page on Facebook to facilitate interaction with customers.  Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         Advanced Medical Claims Analyst     Mar 2012   to   Dec 2013      Company Name   －   City  ,   State     Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         Assistant General Manager     Jun 2010   to   Dec 2010      Company Name   －   City  ,   State     Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  Handled daily operations and reported directly to the corporate office.  Hired and trained staff on overall objectives and goals with an emphasis on high customer service.  Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.         Executive Support / Marketing Assistant     Jul 2007   to   Jun 2010      Company Name   －   City  ,   State     Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.  Managed front-end operations to ensure friendly and efficient transactions.  Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         Reservation & Front Office Manager     Jun 2004   to   Jul 2007      Company Name   －   City  ,   State          Owner/ Partner     Dec 2001   to   May 2004      Company Name   －   City  ,   State          Price Integrity Coordinator     Aug 1999   to   Dec 2001      Company Name   －   City  ,   State          Education      N/A  ,   Business Administration   1999     Jefferson College   －   City  ,   State       Business Administration  Marketing / Advertising         High School Diploma  ,   College Prep. studies   1998     Sainte Genevieve Senior High   －   City  ,   State       Awarded American Shrubel Leadership Scholarship to Jefferson College         Skills     Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.

In [44]:
job_description = """
Data Scientist

Required Skills:
Python
Machine Learning
SQL
Pandas
NumPy
Scikit-learn
Data Visualization
Statistics
"""

In [45]:
skills = [
    "python",
    "machine learning",
    "sql",
    "pandas",
    "numpy",
    "scikit-learn",
    "data visualization",
    "statistics",
    "excel",
    "java",
    "power bi",
    "tableau"
]

In [46]:
resume_text = df['Resume_str'][0].lower()

found_skills = []

for skill in skills:
    if skill in resume_text:
        found_skills.append(skill)

print(found_skills)

['statistics']

In [47]:
df['Category'].value_counts()

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
ADVOCATE                  118
CHEF                      118
ENGINEERING               118
ACCOUNTANT                118
FINANCE                   118
FITNESS                   117
AVIATION                  117
SALES                     116
BANKING                   115
HEALTHCARE                115
CONSULTANT                115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [48]:
df[df['Category'] == 'Data Science'].head()

Empty DataFrame
Columns: [ID, Resume_str, Resume_html, Category]
Index: []

In [49]:
it_resume = df[df['Category'] == 'INFORMATION-TECHNOLOGY']

it_resume.head()

,ID,Resume_str,Resume_html,Category
217,36856210,INFORMATION TECHNOLOGY Summar...,"<div class=""fontsize fontface vmargins hmargin...",INFORMATION-TECHNOLOGY
218,21780877,INFORMATION TECHNOLOGY SPECIALIST\tGS...,"<div class=""fontsize fontface vmargins hmargin...",INFORMATION-TECHNOLOGY
219,33241454,INFORMATION TECHNOLOGY SUPERVISOR ...,"<div class=""fontsize fontface vmargins hmargin...",INFORMATION-TECHNOLOGY
220,25990239,INFORMATION TECHNOLOGY INSTRUCTOR ...,"<div class=""fontsize fontface vmargins hmargin...",INFORMATION-TECHNOLOGY
221,16899268,INFORMATION TECHNOLOGY MANAGER/ANALYS...,"<div class=""fontsize fontface vmargins hmargin...",INFORMATION-TECHNOLOGY

In [50]:
print(it_resume['Resume_str'].iloc[0])

         INFORMATION TECHNOLOGY         Summary     Dedicated  Information Assurance Professional  well-versed in analyzing and mitigating risk and finding cost-effective solutions. Excels at boosting performance and productivity by establishing realistic goals and enforcing deadlines.  Versatile IT professional with 37 years of Enterprise design and engineering methodology.       Skills          Enterprise platforms  Knowledge of Product Lifecycle Management (PLM)  Project tracking  Hardware and software upgrade planning  Product requirements documentation  Self-directed  MS Visio  Decisive  Collaborative  Domain Active Directory Layout  Data storage engineering      Information Assurance  Risk Management Framework (RMF)  Active Directory design and deployment  Workstation build and deployment  Systems Accreditation Packages  Red Hat Enterprise Linux installation and hardening  Network Design & Troubleshooting   High Performance Computing            Experience      Company Name    City  ,   State    Information Technology   02/2011   to   Current        I was hired to manage accreditation
efforts for a major department modernization project involving 3
accreditation packages each leading to successful Authorization To
Operate decisions.  Responsibilities then increased to include all
departmental accreditation efforts leading to another 3 successful
ATOs.  Now, working on 4 new accreditation including
re-authorization for an existing project.  Succeeded in writing and
implementing vulnerability management for existing accredited
systems.





Success
of the accreditation hinged on coordination with ONI Enterprise in
critical design decisions and to help the program integrate smoothly
into the Enterprise thru many meetings, analyzing the Enterprise
business model to understand the best fit for the program.





The
different projects required careful management of specific STIG
compliance and hardening for the different configurations and
services required for the specific domain to be integrated.   Analyzed complex computer systems to assess vulnerability and risk.    Supervised  5  external computer consultants and vendors.    Managed application patches, data backup, security changes and network configuration.           Company Name    City  ,   State    Systems Engineer   02/2006   to   02/2011        I was Hired
to initiate processing strategies in fulfilling department analyst requirements.  Requirements were fulfilled thru i dentifying product problems and strengths and collected data on customer experience  and review of Enterprise compliance to transition to new
technology for supporting new processing needs thru proper processing
power.  The next challenge  came as storage requirements for better performance and more
controlled uses.  After careful study of local infrastructure design, a local storage with off the shelf solutions was
adopted to grow local storage to over 200TB.  In using this solution,
the department saved just over a million dollars in purchasing and
maintenance costs compared to the alternative. Next came requirements to improve processing of future big data formats fulfilled in a Red Hat Linux high compute cluster I designed, purchased and
accredited for operation in the Enterprise.  Improvement on big data analytical processing reduced time from
30 hours to 30 minutes as well as allow for more robust data thru
higher selections of sensors, frequencies and range than allowed thru
the traditional process.         Company Name    City  ,   State    Senior Systems Analyst   02/1999   to   02/2006        I was hired to improve corporate and
client communications and processing requirements which resulted in
the design, build and deployment of 3 Enterprise network solutions.  One
solution resulted in expanding capabilities to supporting Washington
Navy Yard, Norfolk Virginia and Hawaii support facilities.






Fulfilled
requirements for detecting crucial network software/hardware
weaknesses and developing preventive strategies and solutions for
avoiding interruptions and increasing system security thru
documenting system layouts, wiring diagrams and addressing schema to
understand layouts and make informed solutions to upper management.



          Education and Training      Associate of Science  :  Electronic Engineering   1980     Florence Darlington Technical School  ,   City  ,   State       Electronic Engineering.     Dean's list for high GPA.      Class President for second year          Skills        Active Directory  Hardware Engineering  Information Technology  Red Hat Enterprise Linux Servers  MS Windows Servers  MS Windows Desktop  Network Design & Troubleshooting  Architectural Diagrams  Accreditation Boundarys  Risk Management  Enterprise Strategies  Vendor Relations   Desktop Publishing Software: Photoshop, Illustrator, HTML  Team Work  Collaboration

In [51]:
resume_text = it_resume['Resume_str'].iloc[0].lower()

found_skills = []

for skill in skills:
    if skill in resume_text:
        found_skills.append(skill)

print(found_skills)

['excel']

In [52]:
skills = [
    "python",
    "sql",
    "java",
    "machine learning",
    "pandas",
    "numpy",
    "statistics",
    "excel"
]

resume_text = it_resume['Resume_str'].iloc[0].lower()

found_skills = []

for skill in skills:
    if skill in resume_text:
        found_skills.append(skill)

print("Skills Found:")
print(found_skills)

Skills Found:
['excel']

In [53]:
job_skills = [
    "python",
    "sql",
    "java",
    "machine learning",
    "pandas",
    "numpy",
    "statistics",
    "excel"
]

scores = []

for index, row in df.iterrows():
    resume_text = str(row['Resume_str']).lower()

    score = 0

    for skill in job_skills:
        if skill in resume_text:
            score += 1

    percentage = (score / len(job_skills)) * 100

    scores.append(percentage)

df['Score'] = scores

In [54]:
df[['Category', 'Score']].head()

  Category  Score
0       HR   12.5
1       HR    0.0
2       HR   12.5
3       HR   12.5
4       HR   12.5

In [55]:
top_candidates = df.sort_values(by='Score', ascending=False)

top_candidates[['Category', 'Score']].head(10)

                    Category  Score
1762             ENGINEERING   75.0
1348              AUTOMOBILE   75.0
1339              AUTOMOBILE   75.0
926              AGRICULTURE   62.5
315   INFORMATION-TECHNOLOGY   62.5
291   INFORMATION-TECHNOLOGY   62.5
1766             ENGINEERING   50.0
662     BUSINESS-DEVELOPMENT   50.0
1218              CONSULTANT   50.0
1303           DIGITAL-MEDIA   50.0

In [56]:
top_candidates[['Category', 'Score']].head(10)

                    Category  Score
1762             ENGINEERING   75.0
1348              AUTOMOBILE   75.0
1339              AUTOMOBILE   75.0
926              AGRICULTURE   62.5
315   INFORMATION-TECHNOLOGY   62.5
291   INFORMATION-TECHNOLOGY   62.5
1766             ENGINEERING   50.0
662     BUSINESS-DEVELOPMENT   50.0
1218              CONSULTANT   50.0
1303           DIGITAL-MEDIA   50.0

In [57]:
def get_matched_skills(resume_text, job_skills):
    matched = []

    for skill in job_skills:
        if skill in resume_text.lower():
            matched.append(skill)

    return matched

In [58]:
df['Matched_Skills'] = df['Resume_str'].apply(
    lambda x: get_matched_skills(str(x), job_skills)
)

df[['Category', 'Score', 'Matched_Skills']].head()

  Category  Score Matched_Skills
0       HR   12.5   [statistics]
1       HR    0.0             []
2       HR   12.5        [excel]
3       HR   12.5        [excel]
4       HR   12.5        [excel]

In [59]:
def get_missing_skills(resume_text, job_skills):
    missing = []

    for skill in job_skills:
        if skill not in resume_text.lower():
            missing.append(skill)

    return missing

In [60]:
df['Missing_Skills'] = df['Resume_str'].apply(
    lambda x: get_missing_skills(str(x), job_skills)
)

df[['Category', 'Score', 'Matched_Skills', 'Missing_Skills']].head()

,Category,Score,Matched_Skills,Missing_Skills
0,HR,12.5,[statistics],"[python, sql, java, machine learning, pandas, ..."
1,HR,0.0,[],"[python, sql, java, machine learning, pandas, ..."
2,HR,12.5,[excel],"[python, sql, java, machine learning, pandas, ..."
3,HR,12.5,[excel],"[python, sql, java, machine learning, pandas, ..."
4,HR,12.5,[excel],"[python, sql, java, machine learning, pandas, ..."

In [61]:
top_candidates = df.sort_values(
    by='Score',
    ascending=False
)

top_candidates.to_csv(
    '../output/top_candidates.csv',
    index=False
)

print("Top candidates saved successfully!")

Top candidates saved successfully!

In [62]:
df['Matched_Skills'] = df['Resume_str'].apply(
    lambda x: get_matched_skills(str(x), job_skills)
)

df['Missing_Skills'] = df['Resume_str'].apply(
    lambda x: get_missing_skills(str(x), job_skills)
)

df[['Category', 'Score', 'Matched_Skills', 'Missing_Skills']].head()

,Category,Score,Matched_Skills,Missing_Skills
0,HR,12.5,[statistics],"[python, sql, java, machine learning, pandas, ..."
1,HR,0.0,[],"[python, sql, java, machine learning, pandas, ..."
2,HR,12.5,[excel],"[python, sql, java, machine learning, pandas, ..."
3,HR,12.5,[excel],"[python, sql, java, machine learning, pandas, ..."
4,HR,12.5,[excel],"[python, sql, java, machine learning, pandas, ..."

In [63]:
job_description = """
Data Scientist

Skills Required:
Python
Machine Learning
SQL
Pandas
NumPy
Statistics
"""

In [64]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [65]:
resume_text = df['Resume_str'][0]

documents = [job_description, resume_text]

tfidf = TfidfVectorizer()

matrix = tfidf.fit_transform(documents)

similarity = cosine_similarity(matrix[0:1], matrix[1:2])

print("Similarity Score:", similarity[0][0] * 100)

Similarity Score: 2.621164601502149

In [66]:
scores = []

for resume in df['Resume_str']:

    documents = [job_description, str(resume)]

    tfidf = TfidfVectorizer()

    matrix = tfidf.fit_transform(documents)

    similarity = cosine_similarity(
        matrix[0:1],
        matrix[1:2]
    )

    scores.append(similarity[0][0] * 100)

df['Similarity_Score'] = scores

In [67]:
top_candidates = df.sort_values(
    by='Similarity_Score',
    ascending=False
)

top_candidates[
    ['Category', 'Similarity_Score']
].head(10)

                    Category  Similarity_Score
1218              CONSULTANT         11.215741
1339              AUTOMOBILE          9.082038
1303           DIGITAL-MEDIA          8.465453
1040                   SALES          8.109865
1762             ENGINEERING          7.935061
1142              CONSULTANT          7.906185
1348              AUTOMOBILE          7.756089
331   INFORMATION-TECHNOLOGY          6.807313
2184                 BANKING          6.291885
315   INFORMATION-TECHNOLOGY          6.213398

In [68]:
top_candidates[['Category','Similarity_Score']].head(10)

                    Category  Similarity_Score
1218              CONSULTANT         11.215741
1339              AUTOMOBILE          9.082038
1303           DIGITAL-MEDIA          8.465453
1040                   SALES          8.109865
1762             ENGINEERING          7.935061
1142              CONSULTANT          7.906185
1348              AUTOMOBILE          7.756089
331   INFORMATION-TECHNOLOGY          6.807313
2184                 BANKING          6.291885
315   INFORMATION-TECHNOLOGY          6.213398

In [70]:
import os

os.makedirs("output", exist_ok=True)

In [71]:
df.to_csv("output/final_ranking.csv", index=False)

In [72]:
import os
os.makedirs("output", exist_ok=True)

df.to_csv("output/final_ranking.csv", index=False)

In [73]:
import os

print(os.listdir("output"))

['final_ranking.csv']

In [74]:
import pandas as pd

df_check = pd.read_csv("output/final_ranking.csv")
df_check.head()

,ID,Resume_str,Resume_html,Category,Score,Matched_Skills,Missing_Skills,Similarity_Score
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR,12.5,['statistics'],"['python', 'sql', 'java', 'machine learning', ...",2.621165
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR,0.0,[],"['python', 'sql', 'java', 'machine learning', ...",0.213202
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR,12.5,['excel'],"['python', 'sql', 'java', 'machine learning', ...",0.305451
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR,12.5,['excel'],"['python', 'sql', 'java', 'machine learning', ...",1.075057
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR,12.5,['excel'],"['python', 'sql', 'java', 'machine learning', ...",0.719049